version: 0.2

run-as: bm-agent

phases:
  build:
    run-as: root
    commands:
      - bundle install --path=/home/bm-agent/.bundler
      - bundle exec omnibus build bm-agent
artifacts:
  files:
    - pkg/bm-agent-1.0.0-0.el7.x86_64.rpm
  discard-paths: yes
cache:
  paths:
    - '/var/cache/omnibus/**/*'
